# Generated by Django 4.2.6 on 2023-11-01 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(help_text='El codigo de articulo. ', max_length=25)),
                ('descripcion', models.CharField(help_text='La descripcion del articulo. ', max_length=150)),
                ('factor_compra', models.IntegerField(help_text='El factor compra. ')),
                ('factor_reparto', models.IntegerField(help_text='El factor venta. ')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_documento', models.CharField(help_text='El nro.documento de la empresa. ', max_length=11)),
                ('razon_social', models.CharField(help_text='La razón social de la empresa. ', max_length=150)),
                ('direccion', models.CharField(help_text='La direccion de la empresa. ', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='grupos_proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_grupo', models.CharField(help_text='El codigo del grupo. ', max_length=15)),
                ('grupo_descripcion', models.CharField(help_text='La descripcion del grupo. ', max_length=100)),
                ('activo', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], max_length=1, verbose_name='La validacion de situacion es. ')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='inventarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inventario', models.DateTimeField(auto_now_add=True, help_text='La fecha de inventario. ')),
                ('nro_inventario', models.FloatField(help_text='El nro.inventario. ')),
                ('hora_inicio', models.DateTimeField(help_text='Hora de inicio de inventario. ', null=True)),
                ('hora_fin', models.DateTimeField(help_text='Hora de final de inventario. ', null=True)),
                ('estado', models.CharField(choices=[('1', 'Finalizado'), ('0', 'Proceso')], max_length=1, verbose_name='La validacion de situacion es. ')),
                ('creado_por', models.CharField(help_text='Fue creado por. ', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='La fecha de creacion de inventario. ')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='lineas_articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_linea', models.CharField(help_text='El codigo de la linea de articulos. ', max_length=15)),
                ('linea_descripcion', models.CharField(help_text='La descripcion de la linea de articulos. ', max_length=100)),
                ('activo', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], max_length=1, verbose_name='La validacion de situacion es. ')),
                ('grupos_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.grupos_proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_marca', models.CharField(help_text='El codigo de la marca. ', max_length=14)),
                ('marca_nombre', models.CharField(help_text='El nombre de la marca. ', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades_medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_medida_id', models.CharField(help_text='El id de la unidad de medida. ', max_length=10)),
                ('unidad_nombre', models.CharField(help_text='El nombre de la unidad de medida. ', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='El nombre completo del usuario. ', max_length=100)),
                ('email', models.EmailField(help_text='El correo electronico del usuario. ', max_length=254)),
                ('password', models.CharField(help_text='La contraseña del usuario. ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(help_text='El nombre comercial de la empresa. ', max_length=150)),
                ('direccion', models.CharField(help_text='La direccion de la empresa. ', max_length=150)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='sublineas_articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sublinea', models.CharField(help_text='El codigo de la sublinea. ', max_length=15)),
                ('sublinea_descripcion', models.CharField(help_text='La descripcion de la sublinea. ', max_length=100)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], max_length=1, verbose_name='La validacion de estado es. ')),
                ('lineas_articulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.lineas_articulos')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personal', models.CharField(help_text='El nombre del trabajador. ', max_length=100)),
                ('direccion_personal', models.CharField(help_text='La direccion del trabajador. ', max_length=150)),
                ('tipo_documento', models.CharField(choices=[('1', 'Dni'), ('0', 'Carnet')], max_length=1, verbose_name='El tipo de documento del trabajador. ')),
                ('nro_documento', models.CharField(help_text='El nro.documento del trabajador. ', max_length=11)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='items_inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_item', models.IntegerField(help_text='El numero de item. ')),
                ('stock_fisico', models.FloatField(help_text='El stock fisico. ', max_length=12)),
                ('devoluciones_pendientes', models.FloatField(help_text='Las devoluciones pendientes. ', max_length=12)),
                ('total_unidades_stock', models.FloatField(help_text='El total de unidades en stock. ', max_length=12)),
                ('precio_costo', models.FloatField(help_text='El precio. ', max_length=12)),
                ('total_item', models.FloatField(help_text='El total. ', max_length=12)),
                ('Articulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.articulos')),
                ('inventarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.inventarios')),
            ],
        ),
        migrations.AddField(
            model_name='inventarios',
            name='Personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.personal'),
        ),
        migrations.AddField(
            model_name='inventarios',
            name='Sucursales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.sucursales'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='Empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.empresa'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='Unidades_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.unidades_medida'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='grupos_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.grupos_proveedor'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='lineas_articulos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.lineas_articulos'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='marcas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.marcas'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='sublineas_articulos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servinorte_r.sublineas_articulos'),
        ),
    ]
